a = input('digite algo:')
print('O tipo primitivo é',type(a))
print('contem espaços?',a.isspace())
print('é um numero?',a.isnumeric())
print('é alfabetico?',a.isalpha())
print('é alfanumerico?',a.isalnum())
print('está em maiuscula?',a.isupper())
print('está em minuscula?',a.islower())
print('está capilazada?',a.istitle())
