name = input('Qual o seu nome completo?')
up = name.upper()
low = name.lower()
spc = name.strip()
cnt = name.count('')
splt = name.split()
namespc = len(name.replace(' ',''))
name1 = len(splt[0])
print('Seu nome em maiúsculo ficaria: {} \nSeu nome em minúsculo fica: {} \nO número de letras do seu nome é {} \nAs letras só do seu primeiro nome é {}'.format(up,low,namespc,name1))